In [1]:
#mount driver with data
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [2]:
!pip install seaborn==0.9.0
!pip install pandas==0.23.4

In [0]:
#read data
import pandas as pd
import numpy as np
import tensorflow as tf
import os
import math

hilary = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/Trump v.s. Hilary/data/HillaryClinton2014-01-01To2016-10-14Tweets.csv")
trump = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/Trump v.s. Hilary/data/DonaldTrump2014-01-01To2016-10-14Tweets.csv")

In [4]:
hilary.head(10)

Unnamed: 0               date                  id  \
0           0              Oct 9  785272428905791488   
1           1              Oct 9  785325012152713216   
2           2              Oct 9  785282982261190656   
3           3    7m7 minutes ago  786963642080227328   
4           4  29m29 minutes ago  786958117531742208   
5           5  35m35 minutes ago  786956647306522624   
6           6  36m36 minutes ago  786956397766385664   
7           7  38m38 minutes ago  786955912409907200   
8           8  44m44 minutes ago  786954388682203136   
9           9  45m45 minutes ago  786954200584454144   

                                        link  retweet  \
0  /HillaryClinton/status/785272428905791489    False   
1  /HillaryClinton/status/785325012152713216    False   
2  /HillaryClinton/status/785282982261190656    False   
3  /HillaryClinton/status/786963642080227328    False   
4  /HillaryClinton/status/786958117531742208    False   
5  /HillaryClinton/status/786956647306522624    False   
6  /HillaryClinton/status/786956397766385665    False   
7  /HillaryClinton/status/786955912409907200    False   
8  /HillaryClinton/status/786954388682203141    False   
9  /HillaryClinton/status/786954200584454144    False   

                                                text          author  
0        Remember. #Debatepic.twitter.com/rlMbTt5WwY  HillaryClinton  
1  She won. http://hrc.io/2dQkjip  #Debatepic.twi...  HillaryClinton  
2        Let's go. #Debatepic.twitter.com/HD3ZVJ9xl8  HillaryClinton  
3  "Everyone knows how bright she is and how resi...  HillaryClinton  
4  "All the progress we've made these last 8 year...  HillaryClinton  
5  "You have a chance to reject the politics of f...  HillaryClinton  
6  "Change is possible, but it doesn’t just depen...  HillaryClinton  
7  "She knows that in a democracy as big and dive...  HillaryClinton  
8  "He may be up at 3am, but it’s because he’s tw...  HillaryClinton  
9  “She's got the knowledge and experience and th...  HillaryClinton

In [5]:
trump.head(10)

Unnamed: 0               date                  id  \
0           0              Oct 7  784609194234306560   
1           1             Oct 10  785608815962099712   
2           2              Oct 8  784840992734064640   
3           3             Oct 11  785979396620324864   
4           4             Oct 10  785561269571026944   
5           5  38m38 minutes ago  786950598826532864   
6           6    15h15 hours ago  786737820669009920   
7           7             Oct 12  786201435486781440   
8           8             Oct 11  786054986534969344   
9           9             Oct 11  785885793340448768   

                                         link  retweet  \
0  /realDonaldTrump/status/784609194234306560    False   
1  /realDonaldTrump/status/785608815962099712    False   
2  /realDonaldTrump/status/784840992734064641    False   
3  /realDonaldTrump/status/785979396620324865    False   
4  /realDonaldTrump/status/785561269571026946    False   
5  /realDonaldTrump/status/786950598826532864    False   
6  /realDonaldTrump/status/786737820669009921    False   
7  /realDonaldTrump/status/786201435486781440    False   
8  /realDonaldTrump/status/786054986534969344    False   
9  /realDonaldTrump/status/785885793340448769    False   

                                                text       author  
0    Here is my statement.pic.twitter.com/WAZiGoQqMQ  DonaldTrump  
1  Is this really America? Terrible!pic.twitter.c...  DonaldTrump  
2  The media and establishment want me out of the...  DonaldTrump  
3  Wow, @CNN Town Hall questions were given to Cr...  DonaldTrump  
4  Debate polls look great - thank you!\n#MAGA #A...  DonaldTrump  
5  WHAT THEY ARE SAYING ABOUT THE CLINTON CAMPAIG...  DonaldTrump  
6  Thank you to our U.S. Navy for protecting our ...  DonaldTrump  
7  Very little pick-up by the dishonest media of ...  DonaldTrump  
8  Thank you Florida- a MOVEMENT that has never b...  DonaldTrump  
9  The very foul mouthed Sen. John McCain begged ...  DonaldTrump

In [6]:
hilary.describe(include='all')

Unnamed: 0    date            id  \
count   3256.000000    3256  3.256000e+03   
unique          NaN     571           NaN   
top             NaN  Jul 27           NaN   
freq            NaN      50           NaN   
mean    1627.500000     NaN  7.033350e+17   
std      940.070565     NaN  5.586073e+16   
min        0.000000     NaN  5.561633e+17   
25%      813.750000     NaN  6.586402e+17   
50%     1627.500000     NaN  7.078762e+17   
75%     2441.250000     NaN  7.552276e+17   
max     3255.000000     NaN  7.869636e+17   

                                             link retweet  \
count                                        3256    3256   
unique                                       3256       1   
top     /HillaryClinton/status/750415877456232448   False   
freq                                            1    3256   
mean                                          NaN     NaN   
std                                           NaN     NaN   
min                                           NaN     NaN   
25%                                           NaN     NaN   
50%                                           NaN     NaN   
75%                                           NaN     NaN   
max                                           NaN     NaN   

                                                     text          author  
count                                                3256            3256  
unique                                               3251               1  
top     You shouldn't have to worry about your paychec...  HillaryClinton  
freq                                                    2            3256  
mean                                                  NaN             NaN  
std                                                   NaN             NaN  
min                                                   NaN             NaN  
25%                                                   NaN             NaN  
50%                                                   NaN             NaN  
75%                                                   NaN             NaN  
max                                                   NaN             NaN

In [7]:
trump.describe(include='all')

Unnamed: 0        date            id  \
count   8439.000000        8439  8.439000e+03   
unique          NaN         979           NaN   
top             NaN  4 Jan 2015           NaN   
freq            NaN          74           NaN   
mean    4219.000000         NaN  5.916873e+17   
std     2436.273794         NaN  9.381397e+16   
min        0.000000         NaN  4.183651e+17   
25%     2109.500000         NaN  5.202411e+17   
50%     4219.000000         NaN  5.889938e+17   
75%     6328.500000         NaN  6.639269e+17   
max     8438.000000         NaN  7.869506e+17   

                                              link retweet  \
count                                         8439    8439   
unique                                        8439       2   
top     /realDonaldTrump/status/728777599560892416   False   
freq                                             1    5760   
mean                                           NaN     NaN   
std                                            NaN     NaN   
min                                            NaN     NaN   
25%                                            NaN     NaN   
50%                                            NaN     NaN   
75%                                            NaN     NaN   
max                                            NaN     NaN   

                             text       author  
count                        8439         8439  
unique                       8391            1  
top     MAKE AMERICA GREAT AGAIN!  DonaldTrump  
freq                            9         8439  
mean                          NaN          NaN  
std                           NaN          NaN  
min                           NaN          NaN  
25%                           NaN          NaN  
50%                           NaN          NaN  
75%                           NaN          NaN  
max                           NaN          NaN

In [8]:
twitter_data = pd.concat([trump,hilary])
twitter_data.head(10)

Unnamed: 0               date                  id  \
0           0              Oct 7  784609194234306560   
1           1             Oct 10  785608815962099712   
2           2              Oct 8  784840992734064640   
3           3             Oct 11  785979396620324864   
4           4             Oct 10  785561269571026944   
5           5  38m38 minutes ago  786950598826532864   
6           6    15h15 hours ago  786737820669009920   
7           7             Oct 12  786201435486781440   
8           8             Oct 11  786054986534969344   
9           9             Oct 11  785885793340448768   

                                         link  retweet  \
0  /realDonaldTrump/status/784609194234306560    False   
1  /realDonaldTrump/status/785608815962099712    False   
2  /realDonaldTrump/status/784840992734064641    False   
3  /realDonaldTrump/status/785979396620324865    False   
4  /realDonaldTrump/status/785561269571026946    False   
5  /realDonaldTrump/status/786950598826532864    False   
6  /realDonaldTrump/status/786737820669009921    False   
7  /realDonaldTrump/status/786201435486781440    False   
8  /realDonaldTrump/status/786054986534969344    False   
9  /realDonaldTrump/status/785885793340448769    False   

                                                text       author  
0    Here is my statement.pic.twitter.com/WAZiGoQqMQ  DonaldTrump  
1  Is this really America? Terrible!pic.twitter.c...  DonaldTrump  
2  The media and establishment want me out of the...  DonaldTrump  
3  Wow, @CNN Town Hall questions were given to Cr...  DonaldTrump  
4  Debate polls look great - thank you!\n#MAGA #A...  DonaldTrump  
5  WHAT THEY ARE SAYING ABOUT THE CLINTON CAMPAIG...  DonaldTrump  
6  Thank you to our U.S. Navy for protecting our ...  DonaldTrump  
7  Very little pick-up by the dishonest media of ...  DonaldTrump  
8  Thank you Florida- a MOVEMENT that has never b...  DonaldTrump  
9  The very foul mouthed Sen. John McCain begged ...  DonaldTrump

In [0]:
twitter_data = twitter_data.loc[twitter_data['retweet'] == False]

In [0]:
twitter_data = twitter_data.drop(columns=['Unnamed: 0','id','retweet','link'])

In [0]:
twitter_data = twitter_data.replace({'DonaldTrump':0,'HillaryClinton':1})

In [0]:
import re

twitter_data['text'] = twitter_data['text'].apply(lambda text: re.sub(r"(?:http|pic.twitter)\S+", "", text))

In [0]:
twitter_data['text'] = twitter_data['text'].apply(lambda text: re.sub("\n"," ",text))

In [14]:
twitter_data

date                                               text  \
0                 Oct 7                              Here is my statement.   
1                Oct 10                  Is this really America? Terrible!   
2                 Oct 8  The media and establishment want me out of the...   
3                Oct 11  Wow, @CNN Town Hall questions were given to Cr...   
4                Oct 10  Debate polls look great - thank you! #MAGA #Am...   
5     38m38 minutes ago  WHAT THEY ARE SAYING ABOUT THE CLINTON CAMPAIG...   
6       15h15 hours ago  Thank you to our U.S. Navy for protecting our ...   
7                Oct 12  Very little pick-up by the dishonest media of ...   
8                Oct 11  Thank you Florida- a MOVEMENT that has never b...   
9                Oct 11  The very foul mouthed Sen. John McCain begged ...   
10               Oct 11  Disloyal R's are far more difficult than Crook...   
11               Oct 11  With the exception of cheating Bernie out of t...   
12               Oct 11  It is so nice that the shackles have been take...   
13               Oct 11  Our very weak and ineffective leader, Paul Rya...   
14               Oct 11  Despite winning the second debate in a landsli...   
15               Oct 10  Wow, @CNN got caught fixing their "focus group...   
16                Oct 9  .@HillaryClinton is NOT above the law! #Debate...   
17                Oct 9  My team of deplorables will be taking over my ...   
18                Oct 9  So many self-righteous hypocrites. Watch their...   
20                Oct 4  Wow, did you just hear Bill Clinton's statemen...   
21                Oct 4  I will be watching the great Governor @Mike_Pe...   
22                Oct 2  Just announced that Iraq (U.S.) is preparing f...   
23                Oct 2  Melania and I extend our warmest greetings to ...   
24                Oct 2  Bernie should pull his endorsement of Crooked ...   
26                Oct 2  I have created tens of thousands of jobs and w...   
27                Oct 2  I know our complex tax laws better than anyone...   
28                Oct 1  Wow, just saw the really bad @CNN ratings. Peo...   
29                Oct 1  The so-called Commission on Presidential Debat...   
30                Oct 1  Crooked H is nasty to Sanders supporters behin...   
31               Sep 30  I believe in #AmericaFirst and that means FAMI...   
...                 ...                                                ...   
3226         8 Apr 2015  Praying for #WalterScott's family. Heartbreaki...   
3227         6 Apr 2015  The detention of women's activists in #China m...   
3228         1 Apr 2015  Like IN law, AR bill goes beyond protecting re...   
3229        27 Mar 2015  Abusive payday lenders take advantage of famil...   
3230        27 Mar 2015  Loved serving w/ @SenatorReid, true friend, pa...   
3231        26 Mar 2015  Sad this new Indiana law can happen in America...   
3232        26 Mar 2015  Protecting pregnant women from discrimination ...   
3233        23 Mar 2015  #ACA@5: 16m covered. Young ppl. Preexisting co...   
3234        17 Mar 2015  Repeal of the ACA would let insurers write the...   
3235        17 Mar 2015  Making college more affordable is an investmen...   
3236        17 Mar 2015  Our nation's future - jobs & economic growth -...   
3237        17 Mar 2015  Budgets reflect our priorities. They should he...   
3238        16 Mar 2015  ...2) Playing politics with trafficking victim...   
3239        16 Mar 2015  Congressional trifecta against women today: 1)...   
3240        11 Mar 2015  GOP letter to Iranian clerics undermines Ameri...   
3241         9 Mar 2015  Excited to share the #NoCeilings data. Hope yo...   
3242         8 Mar 2015  See my new profile pic to raise awareness on h...   
3243         7 Mar 2015  Watched @repjohnlewis & @BarackObama in #Selma...   
3244         4 Mar 2015  I want the public to see my email. I asked Sta...   
3245        25 Feb 2015  Yesterday I met 

In [15]:
import keras
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(nb_words=3000, lower=True,split=' ')
tokenizer.fit_on_texts(twitter_data['text'].values)
X = tokenizer.texts_to_sequences(twitter_data['text'].values)
X = pad_sequences(X)

Y = twitter_data['author'].values
print(X)
print(Y)

Using TensorFlow backend.
/usr/local/lib/python3.6/dist-packages/keras_preprocessing/text.py:177: UserWarning: The `nb_words` argument in `Tokenizer` has been renamed `num_words`.
  warnings.warn('The `nb_words` argument in `Tokenizer` '


[[   0    0    0 ...    7   36  670]
 [   0    0    0 ...  130   46  325]
 [   0    0    0 ...  478  153  829]
 ...
 [   0    0    0 ...    1  530  471]
 [   0    0    0 ...  225  111 1865]
 [   0    0    0 ...  530  471  139]]
[0 0 0 ... 1 1 1]


In [16]:
print(X.shape)
print(Y.shape)

(9016, 32)
(9016,)


In [17]:
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense

model = Sequential()
model.add(Embedding(3000,128,input_length=X.shape[1],dropout=0.2))
model.add(LSTM(200, dropout_U = 0.2, dropout_W = 0.2))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer='adam',metrics = ['accuracy'])
model.summary()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: The `dropout` argument is no longer support in `Embedding`. You can apply a `keras.layers.SpatialDropout1D` layer right after the `Embedding` layer to get the same behavior.
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(200, dropout=0.2, recurrent_dropout=0.2)`
  


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 32, 128)           384000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 200)               263200    
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 201       
Total params: 647,401
Trainable params: 647,401
Non-trainable params: 0
_________________________________________________________________


In [18]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2)
model.fit(X_train,y_train,epochs=32,shuffle=True,verbose=1,validation_data=(X_test, y_test))

Train on 7212 samples, validate on 1804 samples
Epoch 1/32
7212/7212 [==============================] - 24s 3ms/step - loss: 0.3514 - acc: 0.8368 - val_loss: 0.1785 - val_acc: 0.9285
Epoch 2/32
7212/7212 [==============================] - 23s 3ms/step - loss: 0.1229 - acc: 0.9569 - val_loss: 0.1714 - val_acc: 0.9335
Epoch 3/32
7212/7212 [==============================] - 23s 3ms/step - loss: 0.0815 - acc: 0.9687 - val_loss: 0.1831 - val_acc: 0.9324
Epoch 4/32
7212/7212 [==============================] - 23s 3ms/step - loss: 0.0547 - acc: 0.9792 - val_loss: 0.2282 - val_acc: 0.9246
Epoch 5/32
7212/7212 [==============================] - 22s 3ms/step - loss: 0.0410 - acc: 0.9845 - val_loss: 0.2851 - val_acc: 0.9263
Epoch 6/32
7212/7212 [==============================] - 23s 3ms/step - loss: 0.0316 - acc: 0.9893 - val_loss: 0.2368 - val_acc: 0.9274
Epoch 7/32
7212/7212 [==============================] - 23s 3ms/step - loss: 0.0311 - acc: 0.9895 - val_loss: 0.2460 - val_acc: 0.9307
Epoch 8

In [30]:
trump_tweet = 'I wish people would read or listen to my words on the Border Wall.'
hilary_tweet = 'To all the little girls watching...never doubt that you are valuable and powerful & deserving of every chance & opportunity in the world.'
sample = tokenizer.texts_to_sequences([trump_tweet,hilary_tweet])
sample = pad_sequences(sample,maxlen=32)
print(sample)

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0   10  980   35   78  386   77  755    2   36  456
    11    1  245  271]
 [   0    0    0    0    0    0    0    0    0    0    0    0    2   29
     1  458 1365  416   79 1407   15    9   18    4 1645    5  101  506
   556    6    1  152]]


In [0]:
prediction = model.predict_classes(sample)

In [32]:
prediction

array([[0],
       [1]], dtype=int32)